name: Bug Report
description: Report a bug with the ecoNET-300 Home Assistant Integration
title: "[Bug]: "
labels: ["bug"]
assignees: ["jontofront"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: title
    attributes:
      label: Bug Title
      description: A brief description of the bug.
      placeholder: "Enter the bug title here"

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: >-
        Describe the issue you are experiencing here, to communicate to the
        maintainers. Tell us what you were trying to do and what happened.

        Provide a clear and concise description of what the problem is.
      placeholder: "Enter the bug description here"

  - type: checkboxes
    id: devices
    attributes:
      label: "Connected devices"
      description: "I have the following devices connected. For more information, see [ecoNET300_DTR_1.0_ENG](https://thermostahl.ro/wp-content/uploads/2020/08/ecoNET300_DTR_1.0_ENG.pdf)."
      options:
        - label: ecoMAX800 series
        - label: ecoMAX850 series
        - label: ecoMAX860 series
        - label: ecoSTER
        - label: ecoNET 300
    validations:
      required: true

  - type: dropdown
    id: series
    attributes:
      label: Affected Series
      description: Select the series of the ecoMAX controller affected by this bug.
      options:
        - label: Select a series
        - label: ecoMAX800 series
          description: "ecoMAX800 series controllers"
        - label: ecoMAX850 series
          description: "ecoMAX850 series controllers"
        - label: ecoMAX860 series
          description: "ecoMAX860 series controllers"

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the bug.
      placeholder: "Enter the steps to reproduce the bug here"

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
      placeholder: "Enter the expected behavior here"

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: Describe what actually happened.
      placeholder: "Enter the actual behavior here"

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Include any relevant logs or error messages.
      placeholder: "Enter the logs or error messages here"

  - type: input
    id: version
    attributes:
      label: What version of Econet300 integration has the issue?
      description: >
        Enter the version of the ecoNET-300 Home Assistant Integration you are using.

  - type: input
    id: ha_version
    validations:
      required: true
    attributes:
      label: What version of Home Assistant Core has the issue?
      description: >
        Can be found in the System information section of Home Assistant.

        [Open your Home Assistant instance and show the system information.](https://my.home-assistant.io/redirect/system_health/)
        [![Open your Home Assistant instance and show the system information.](https://my.home-assistant.io/badges/system_health.svg)](https://my.home-assistant.io/redirect/system_health/)

  - type: input
    id: last_working_version
    attributes:
      label: What was the last working version of Econet300 integration?
      description: >
        If known, otherwise leave blank.

  - type: markdown
    attributes:
      value: |
        # Details

  - type: textarea
    id: diagnostics
    attributes:
      label: Diagnostics information
      placeholder: "Drag-and-drop diagnostics data file here"
      description: >-
        Follow HA guide to [download diagnostic data](https://www.home-assistant.io/docs/configuration/troubleshooting/#debug-logs-and-diagnostics).

        **It would really help if you could download the diagnostics data for the device you are having issues with,
        and <ins>drag-and-drop that file into the textbox below.</ins>**

        It generally allows pinpointing defects and thus resolving issues faster.